version: "3.7"
services:
  api_service:
    image: tipsontech/mongo-db-ci:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - mongo-express
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      # mongodb://username:password@mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - data:/data/db
volumes:
  data:
    name: my_mongo_db_data
